### PR TITLE
Update guzzle to: 7.5

### PR DESCRIPTION
**Pull request by hossein-git**

### CODE REVIEW

**Comment by ChristopherDosin** [comment]
@vienthuong For another package we need guzzle 7.5 - Would it be possible to update it?

@hossein-git Please also adjust the Changelog and squash the commits after.

**Comment by vienthuong** [comment]
Hi @hossein-git 
Thanks, I merged it

**Comment by vienthuong** [comment]
please update the package to 1.7.1

**Comment by TobiasGraml11** [comment]
@vienthuong I am using this SDK within a Shopware Plugin and the newest Shopware 6 plugin does not support Guzzle 7.5.

Is there any reason, why the version is explicitly set to `^7.5` and can't be `7.x` or `^7.0` or `~7`? The explicit version can then be set by the project using it.
I would say the minimum version should be defined by the feature set of the SDK.

**Comment by TobiasGraml11** [comment]
@vienthuong Thanks!

**Comment by TobiasGraml11** [comment]
@vienthuong Do you want me to create an issue or a PR?

**Comment by vienthuong** [comment]
@TobiasGraml11 sorry I am getting busy recently, it'd be great if you can help me to create a PR otherwise I will do it tmr

**Comment by TobiasGraml11** [comment]
@vienthuong I created a PR: #63

**Pull request merged**
